<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\VisionInspection.Core\VisionInspection.Core.csproj" />
    <ProjectReference Include="..\..\..\..\YoloDotNet\YoloDotNet.csproj" />
    <ProjectReference Include="..\..\..\..\YoloDotNet.ExecutionProvider.Cuda\YoloDotNet.ExecutionProvider.Cuda.csproj" />
    <ProjectReference Include="..\..\..\..\YoloDotNet.ExecutionProvider.Cpu\YoloDotNet.ExecutionProvider.Cpu.csproj" />
  </ItemGroup>

</Project>
